### ISSUE TITLE
As a user, I want to rate a movie and see it’s rating.

### ISSUE THREAD

**Issue by deniskilseev** [deniskilseev/Bee-roll#79]

**Comment by stiruchunapally** [comment]
Can see dummy rating for now. Need backend implementation to get average of all user ratings

**Comment by ArtemiiAkhunov** [comment]
#93 should make the backend working

**Comment by ArtemiiAkhunov** [comment]
#102 should be connecting posts and ratings

**Comment by stiruchunapally** [comment]
#112 Adds reviews and dynamic ratings on movie pages
